name: Pylint

on:
  push:
    branches: [ master, bugs_fix ]
  pull_request:
    branches: [ master, bugs_fix ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: linting
      uses: alexanderdamiani/pylinter@v1.3.0
      with:
        python-root: './edutalk/'
        flake8-flags: '--count --show-source --statistics --max-line-length=185 --ignore=W503,E115,F722,F821,F841 --exclude=.git,__pycache__,./edutalk/fixtures/src/,./edutalk/static'
        mypy-flags: '--exclude ./edutalk/(fixtures|static)/'
        skip-isort: true
